services:
  - type: web
    name: panditji-backend
    runtime: node
    plan: free
    region: Ohio (US East)
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PANDIT_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
